spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security2
    username: postgres
    password: juans1910
    driver-classname: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


